SUPPORTED_AIRPORTS = ["OMDB", "OMAA", "OMSJ", "OMDW", "OMRK", "OTHH", "OOMS", "EGLL", "EGPH", "OBBI", "EFHK", "EDDF", "LHBP"]

ATC_RATING_CONVERSIONS = {"CTR": "C1", "APP": "S3", "TWR": "S2", "GND": "S1", "DEL": "S1"}

PREFIX = "$"