name: Auto Pull Latest Main Branch on VPS

on:
  push:
    branches:
      - main  # Trigger the workflow when main is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start Deployment
        run: echo "GitHub Actions workflow started..."

      - name: Install SSH and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client

      - name: Pull Latest Code on VPS Using Password
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          echo "Connecting to VPS and pulling latest code..."
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
            cd ~/VATSIM-bot-Main  # Change to your actual bot directory
            git pull origin main
            echo "Git pull completed!"
          EOF
